name: Terraform apply

on:
  push:
    branches: ["main"]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  plan:
    name: terraform apply
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init -backend=true

      - name: Terraform Apply
        run: terraform apply -auto-approve
